### ISSUE TITLE
Text overlapping in Firefox Browser

### ISSUE THREAD

**Issue by lmborch** [fuglede/groenstroem-web#48]
![billede](https://user-images.githubusercontent.com/62183483/76686691-9c43df80-661d-11ea-8e7d-a43069ed8a76.png)
Desktop Firefox browser: 74.0 (64-bit)

**Comment by fuglede** [comment]
Thanks for the report! Looks like this is the same issue that occurred in some Android browsers in #41.

Really, the logic for determining the font size should be revamped; right now it's all based on `vmin`, i.e. the font size is based on the smaller of the height and the width of the viewport (the browser window). This works perfectly fine for very narrow screens (phones) and very wide screens (typically desktop browsers), but looks wonky the moment the browser is square-ish.

A simple fix would be to decrease the size altogether, but keeping it large was a conscious decision to help out with accessibility, and a better fix would be to improve the logic altogether (perhaps by using CSS grids and somehow connecting font size to the containing element).

**Comment by fuglede** [comment]
@lmborch: I spent some time fine-tuning the layout. Could I convince you to check it out again? Might require a cache clear (Ctrl+R in Firefox).

**Comment by lmborch** [comment]
I can confirm the fix ;)

**Comment by fuglede** [comment]
Great, thanks for checking, @lmborch!
